---
version: '2'
name: harvester
services:
  cga:
    image: harvardcga/cga-harvester
    external_links:
      - kafka-kafka
    environment:
      TWEET_TOPIC: CGATweets2
      KAFKA_HOST_PORT: kafka-kafka-1:9092,kafka-kafka-2:9092
      COMPRESSION_TYPE: lz4
      ACKS: 1
      RETRIES: 30
      LINGER_MS: 100
      RETRY_BACKOFF_MS: 1000
      APP_PARAMS_NAME: Twerld
      APP_PARAMS_KEY: rIg8zjOpPcvGgWbteJYQ
      USER_1: databases4life
      USER_2: gamalabdalwahid
      USER_3: Velos_MapD
      USER_4: kedahek
      USER_5: tmostak
      OAUTH_TOKEN_USER_1: 1173337286-rhxiLu2YWTmWuKrlwYL6qcBvO5pReLzxli3gfGS
      OAUTH_TOKEN_USER_2: 568766576-9OeLy4k31jH0xGsq9FtnvGYZZBnZUs7oDxTLoQIm
      OAUTH_TOKEN_USER_3: 964655989-DFtRLIqlYtjLIGoolNjLptmpMgTUCkU1u6eUaqBN
      OAUTH_TOKEN_USER_4: 561011150-yKMTb56Gbj1oR5kiRoEM7ZWOv2ScZP8RL3kGZxRl
      OAUTH_TOKEN_USER_5: 1173286686-4xkTwHF3FvnSKGTQHOjhuP1spmZBx1ot7y639oI
      BOUNDING_BOX_1: NWW,databases4life,-180,15,-92,90
      BOUNDING_BOX_2: NWE,gamalabdalwahid,-92,15,-30,90
      BOUNDING_BOX_3: SW,Velos_MapD,-180,-90,-30,15
      BOUNDING_BOX_4: EW,kedahek,-30,-90,60,90
      BOUNDING_BOX_5: EE,tmostak,60,-90,180,90
    secrets:
      - secret: HARVESTER_H_APP_PARAMS_SECRET
        name: APP_PARAMS_SECRET
        type: env
      - secret: HARVESTER_H_OAUTH_USER_1_SECRET
        name: OAUTH_SECRET_USER_1
        type: env
      - secret: HARVESTER_H_OAUTH_USER_2_SECRET
        name: OAUTH_SECRET_USER_2
        type: env
      - secret: HARVESTER_H_OAUTH_USER_3_SECRET
        name: OAUTH_SECRET_USER_3
        type: env
      - secret: HARVESTER_H_OAUTH_USER_4_SECRET
        name: OAUTH_SECRET_USER_4
        type: env
      - secret: HARVESTER_H_OAUTH_USER_5_SECRET
        name: OAUTH_SECRET_USER_5
        type: env
     
      
    
